Fall back to xterm-256color if terminfo isn't found

diff --git a/chezmoi/dot_zshrc b/chezmoi/dot_zshrc
--- a/chezmoi/dot_zshrc
+++ b/chezmoi/dot_zshrc
@@ -1,6 +1,14 @@
 # Path to your oh-my-zsh configuration.
 ZSH=$HOME/.oh-my-zsh
 
+# If the terminfo for the current terminal isn't found, fall back to xterm-256color
+if command -v infocmp &>/dev/null; then
+    if ! infocmp -1 $TERM &>/dev/null; then
+        echo "Could not find definition for $TERM, falling back to xterm-256color"
+        export TERM=xterm-256color
+    fi
+fi
+
 if ! [[ -f ~/.zshrc_local ]]; then
     touch ~/.zshrc_local
 fi
